// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata/v1/metadata_slot.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// rpc RPC (stream CMDRequest) returns (stream CMDResponse);
type ReportType int32

const (
	ReportType_OP_HANDSHAKE       ReportType = 0
	ReportType_OP_HANDSHAKE_REPLY ReportType = 1
	ReportType_OP_HEARTBEAT       ReportType = 2
	ReportType_OP_HEARTBEAT_REPLY ReportType = 3
	ReportType_OP_STATUS          ReportType = 4
	// OP_STATUS_REPLY = 5;
	ReportType_OP_SEND_CMD       ReportType = 10
	ReportType_OP_SEND_CMD_REPLY ReportType = 11
)

var ReportType_name = map[int32]string{
	0:  "OP_HANDSHAKE",
	1:  "OP_HANDSHAKE_REPLY",
	2:  "OP_HEARTBEAT",
	3:  "OP_HEARTBEAT_REPLY",
	4:  "OP_STATUS",
	10: "OP_SEND_CMD",
	11: "OP_SEND_CMD_REPLY",
}

var ReportType_value = map[string]int32{
	"OP_HANDSHAKE":       0,
	"OP_HANDSHAKE_REPLY": 1,
	"OP_HEARTBEAT":       2,
	"OP_HEARTBEAT_REPLY": 3,
	"OP_STATUS":          4,
	"OP_SEND_CMD":        10,
	"OP_SEND_CMD_REPLY":  11,
}

func (x ReportType) String() string {
	return proto.EnumName(ReportType_name, int32(x))
}

func (ReportType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{0}
}

//rpc Range (SubscriptionRangeResponse) returns (stream SubscriptionRangeResponse);
type RestoreRequest struct {
	Header *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// revision is the point-in-time of the key-value store to use for the range.
	// If revision is less or equal to zero, the range is over the newest key-value store.
	// If the revision has been compacted, ErrCompacted is returned as a response.
	Revision             int64    `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{0}
}
func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

type RestoreResponse struct {
	Header *ResponseHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*RestoreResponse_InitConfig
	//	*RestoreResponse_Resource
	//	*RestoreResponse_Subscription
	//	*RestoreResponse_Rules
	Body                 isRestoreResponse_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{1}
}
func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

type isRestoreResponse_Body interface {
	isRestoreResponse_Body()
}

type RestoreResponse_InitConfig struct {
	InitConfig *InitResponse `protobuf:"bytes,10,opt,name=init_config,json=initConfig,proto3,oneof" json:"init_config,omitempty"`
}
type RestoreResponse_Resource struct {
	Resource *ResourceResponse `protobuf:"bytes,11,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
}
type RestoreResponse_Subscription struct {
	Subscription *SubValueResponse `protobuf:"bytes,12,opt,name=subscription,proto3,oneof" json:"subscription,omitempty"`
}
type RestoreResponse_Rules struct {
	Rules *RuleValueResponse `protobuf:"bytes,13,opt,name=rules,proto3,oneof" json:"rules,omitempty"`
}

func (*RestoreResponse_InitConfig) isRestoreResponse_Body()   {}
func (*RestoreResponse_Resource) isRestoreResponse_Body()     {}
func (*RestoreResponse_Subscription) isRestoreResponse_Body() {}
func (*RestoreResponse_Rules) isRestoreResponse_Body()        {}

func (m *RestoreResponse) GetBody() isRestoreResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *RestoreResponse) GetInitConfig() *InitResponse {
	if x, ok := m.GetBody().(*RestoreResponse_InitConfig); ok {
		return x.InitConfig
	}
	return nil
}

func (m *RestoreResponse) GetResource() *ResourceResponse {
	if x, ok := m.GetBody().(*RestoreResponse_Resource); ok {
		return x.Resource
	}
	return nil
}

func (m *RestoreResponse) GetSubscription() *SubValueResponse {
	if x, ok := m.GetBody().(*RestoreResponse_Subscription); ok {
		return x.Subscription
	}
	return nil
}

func (m *RestoreResponse) GetRules() *RuleValueResponse {
	if x, ok := m.GetBody().(*RestoreResponse_Rules); ok {
		return x.Rules
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RestoreResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RestoreResponse_InitConfig)(nil),
		(*RestoreResponse_Resource)(nil),
		(*RestoreResponse_Subscription)(nil),
		(*RestoreResponse_Rules)(nil),
	}
}

type InitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{2}
}
func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

type ResourceResponse struct {
	Source               []*Flow  `protobuf:"bytes,10,rep,name=source,proto3" json:"source,omitempty"`
	Sink                 *Flow    `protobuf:"bytes,11,opt,name=sink,proto3" json:"sink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceResponse) Reset()         { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()    {}
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{3}
}
func (m *ResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceResponse.Unmarshal(m, b)
}
func (m *ResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceResponse.Marshal(b, m, deterministic)
}
func (m *ResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceResponse.Merge(m, src)
}
func (m *ResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceResponse.Size(m)
}
func (m *ResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceResponse proto.InternalMessageInfo

type SubValueResponse struct {
	Subscriptions []*SubscriptionValue `protobuf:"bytes,10,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// more indicates if there are more Subscriptions to return in the requested range.
	More bool `protobuf:"varint,11,opt,name=more,proto3" json:"more,omitempty"`
	// count is set to the number of Subscriptions within the range when requested.
	Count int64 `protobuf:"varint,12,opt,name=count,proto3" json:"count,omitempty"`
	// revision is set to the revision of start range.
	StartRevision        int64    `protobuf:"varint,13,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubValueResponse) Reset()         { *m = SubValueResponse{} }
func (m *SubValueResponse) String() string { return proto.CompactTextString(m) }
func (*SubValueResponse) ProtoMessage()    {}
func (*SubValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{4}
}
func (m *SubValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubValueResponse.Unmarshal(m, b)
}
func (m *SubValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubValueResponse.Marshal(b, m, deterministic)
}
func (m *SubValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubValueResponse.Merge(m, src)
}
func (m *SubValueResponse) XXX_Size() int {
	return xxx_messageInfo_SubValueResponse.Size(m)
}
func (m *SubValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubValueResponse proto.InternalMessageInfo

type RuleValueResponse struct {
	Rules []*RuleValue `protobuf:"bytes,10,rep,name=rules,proto3" json:"rules,omitempty"`
	// more indicates if there are more Rules to return in the requested range.
	More bool `protobuf:"varint,11,opt,name=more,proto3" json:"more,omitempty"`
	// count is set to the number of Rules within the range when requested.
	Count int64 `protobuf:"varint,12,opt,name=count,proto3" json:"count,omitempty"`
	// revision is set to the revision of start range.
	StartRevision        int64    `protobuf:"varint,13,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleValueResponse) Reset()         { *m = RuleValueResponse{} }
func (m *RuleValueResponse) String() string { return proto.CompactTextString(m) }
func (*RuleValueResponse) ProtoMessage()    {}
func (*RuleValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{5}
}
func (m *RuleValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleValueResponse.Unmarshal(m, b)
}
func (m *RuleValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleValueResponse.Marshal(b, m, deterministic)
}
func (m *RuleValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleValueResponse.Merge(m, src)
}
func (m *RuleValueResponse) XXX_Size() int {
	return xxx_messageInfo_RuleValueResponse.Size(m)
}
func (m *RuleValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RuleValueResponse proto.InternalMessageInfo

//rpc Watch (WatchRequest) returns (stream WatchResponse);
type SyncRequest struct {
	Header *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// key is the key to register for watching.
	Key []byte `protobuf:"bytes,10,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the end of the range [key, range_end) to watch. If range_end is not given,
	// only the key argument is watched. If range_end is equal to '\0', all keys greater than
	// or equal to the key argument are watched.
	// If the range_end is one bit larger than the given key,
	// then all keys with the prefix (the given key) will be watched.
	RangeEnd []byte `protobuf:"bytes,11,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
	StartRevision int64 `protobuf:"varint,12,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	// If watch_id is provided and non-zero, it will be assigned to this watcher.
	// Since creating a watcher in etcd is not a synchronous operation,
	// this can be used ensure that ordering is correct when creating multiple
	// watchers on the same stream. Creating a watcher with an ID already in
	// use on the stream will cause an error to be returned.
	WatchId              int64    `protobuf:"varint,13,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{6}
}
func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

type RuleWatchResponse struct {
	Events               []*RuleEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RuleWatchResponse) Reset()         { *m = RuleWatchResponse{} }
func (m *RuleWatchResponse) String() string { return proto.CompactTextString(m) }
func (*RuleWatchResponse) ProtoMessage()    {}
func (*RuleWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{7}
}
func (m *RuleWatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleWatchResponse.Unmarshal(m, b)
}
func (m *RuleWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleWatchResponse.Marshal(b, m, deterministic)
}
func (m *RuleWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleWatchResponse.Merge(m, src)
}
func (m *RuleWatchResponse) XXX_Size() int {
	return xxx_messageInfo_RuleWatchResponse.Size(m)
}
func (m *RuleWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RuleWatchResponse proto.InternalMessageInfo

type SyncResponse struct {
	Header *ResponseHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// watch_id is the ID of the watcher that corresponds to the response.
	WatchId int64 `protobuf:"varint,10,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*SyncResponse_InitConfig
	//	*SyncResponse_Subscription
	//	*SyncResponse_Rules
	Body                 isSyncResponse_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{8}
}
func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (m *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(m, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

type isSyncResponse_Body interface {
	isSyncResponse_Body()
}

type SyncResponse_InitConfig struct {
	InitConfig *SlotEventResponse `protobuf:"bytes,11,opt,name=init_config,json=initConfig,proto3,oneof" json:"init_config,omitempty"`
}
type SyncResponse_Subscription struct {
	Subscription *SubEventResponse `protobuf:"bytes,12,opt,name=subscription,proto3,oneof" json:"subscription,omitempty"`
}
type SyncResponse_Rules struct {
	Rules *RuleEventResponse `protobuf:"bytes,13,opt,name=rules,proto3,oneof" json:"rules,omitempty"`
}

func (*SyncResponse_InitConfig) isSyncResponse_Body()   {}
func (*SyncResponse_Subscription) isSyncResponse_Body() {}
func (*SyncResponse_Rules) isSyncResponse_Body()        {}

func (m *SyncResponse) GetBody() isSyncResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *SyncResponse) GetInitConfig() *SlotEventResponse {
	if x, ok := m.GetBody().(*SyncResponse_InitConfig); ok {
		return x.InitConfig
	}
	return nil
}

func (m *SyncResponse) GetSubscription() *SubEventResponse {
	if x, ok := m.GetBody().(*SyncResponse_Subscription); ok {
		return x.Subscription
	}
	return nil
}

func (m *SyncResponse) GetRules() *RuleEventResponse {
	if x, ok := m.GetBody().(*SyncResponse_Rules); ok {
		return x.Rules
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SyncResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SyncResponse_InitConfig)(nil),
		(*SyncResponse_Subscription)(nil),
		(*SyncResponse_Rules)(nil),
	}
}

type SlotEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlotEventResponse) Reset()         { *m = SlotEventResponse{} }
func (m *SlotEventResponse) String() string { return proto.CompactTextString(m) }
func (*SlotEventResponse) ProtoMessage()    {}
func (*SlotEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{9}
}
func (m *SlotEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlotEventResponse.Unmarshal(m, b)
}
func (m *SlotEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlotEventResponse.Marshal(b, m, deterministic)
}
func (m *SlotEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotEventResponse.Merge(m, src)
}
func (m *SlotEventResponse) XXX_Size() int {
	return xxx_messageInfo_SlotEventResponse.Size(m)
}
func (m *SlotEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SlotEventResponse proto.InternalMessageInfo

type SubEventResponse struct {
	Events               []*SubscriptionEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubEventResponse) Reset()         { *m = SubEventResponse{} }
func (m *SubEventResponse) String() string { return proto.CompactTextString(m) }
func (*SubEventResponse) ProtoMessage()    {}
func (*SubEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{10}
}
func (m *SubEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubEventResponse.Unmarshal(m, b)
}
func (m *SubEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubEventResponse.Marshal(b, m, deterministic)
}
func (m *SubEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubEventResponse.Merge(m, src)
}
func (m *SubEventResponse) XXX_Size() int {
	return xxx_messageInfo_SubEventResponse.Size(m)
}
func (m *SubEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubEventResponse proto.InternalMessageInfo

type RuleEventResponse struct {
	Events               []*RuleEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RuleEventResponse) Reset()         { *m = RuleEventResponse{} }
func (m *RuleEventResponse) String() string { return proto.CompactTextString(m) }
func (*RuleEventResponse) ProtoMessage()    {}
func (*RuleEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{11}
}
func (m *RuleEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleEventResponse.Unmarshal(m, b)
}
func (m *RuleEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleEventResponse.Marshal(b, m, deterministic)
}
func (m *RuleEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleEventResponse.Merge(m, src)
}
func (m *RuleEventResponse) XXX_Size() int {
	return xxx_messageInfo_RuleEventResponse.Size(m)
}
func (m *RuleEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RuleEventResponse proto.InternalMessageInfo

// rpc Report (ReportRequest) returns (ReportResponse);
// Used to report telemetry after performing one or more actions.
type ReportRequest struct {
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Ver                  string         `protobuf:"bytes,4,opt,name=ver,proto3" json:"ver,omitempty"`
	ResourceId           string         `protobuf:"bytes,10,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Type                 ReportType     `protobuf:"varint,11,opt,name=type,proto3,enum=mdmp.metadata.ReportType" json:"type,omitempty"`
	Payload              []byte         `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{12}
}
func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

// Used to carry responses to telemetry reports
type ReportResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9b5dc549bd839ae, []int{13}
}
func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("mdmp.metadata.ReportType", ReportType_name, ReportType_value)
	proto.RegisterType((*RestoreRequest)(nil), "mdmp.metadata.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "mdmp.metadata.RestoreResponse")
	proto.RegisterType((*InitResponse)(nil), "mdmp.metadata.InitResponse")
	proto.RegisterType((*ResourceResponse)(nil), "mdmp.metadata.ResourceResponse")
	proto.RegisterType((*SubValueResponse)(nil), "mdmp.metadata.SubValueResponse")
	proto.RegisterType((*RuleValueResponse)(nil), "mdmp.metadata.RuleValueResponse")
	proto.RegisterType((*SyncRequest)(nil), "mdmp.metadata.SyncRequest")
	proto.RegisterType((*RuleWatchResponse)(nil), "mdmp.metadata.RuleWatchResponse")
	proto.RegisterType((*SyncResponse)(nil), "mdmp.metadata.SyncResponse")
	proto.RegisterType((*SlotEventResponse)(nil), "mdmp.metadata.SlotEventResponse")
	proto.RegisterType((*SubEventResponse)(nil), "mdmp.metadata.SubEventResponse")
	proto.RegisterType((*RuleEventResponse)(nil), "mdmp.metadata.RuleEventResponse")
	proto.RegisterType((*ReportRequest)(nil), "mdmp.metadata.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "mdmp.metadata.ReportResponse")
}

func init() { proto.RegisterFile("metadata/v1/metadata_slot.proto", fileDescriptor_d9b5dc549bd839ae) }

var fileDescriptor_d9b5dc549bd839ae = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0x93, 0x6c, 0xda, 0x3e, 0x3b, 0x5d, 0xf7, 0x15, 0x90, 0x37, 0x85, 0x36, 0xb2, 0x84,
	0xa8, 0x40, 0x9b, 0x74, 0x03, 0x88, 0xbd, 0x80, 0x94, 0xb6, 0x5e, 0xda, 0x65, 0xff, 0x54, 0x93,
	0x00, 0x82, 0x8b, 0xe5, 0xc4, 0xb3, 0xa9, 0xb5, 0x8e, 0xc7, 0x78, 0xc6, 0x59, 0xe5, 0x7b, 0x20,
	0x71, 0xe0, 0x0b, 0x20, 0x21, 0x71, 0xe2, 0x0b, 0x70, 0xe3, 0xc8, 0x57, 0x58, 0x3e, 0x01, 0x47,
	0x8e, 0xc8, 0x63, 0x3b, 0x9b, 0x38, 0xae, 0x16, 0x14, 0x6e, 0xf3, 0x66, 0x7e, 0xbf, 0xf7, 0x7e,
	0xef, 0xbd, 0x79, 0x63, 0xc3, 0xd1, 0x94, 0x0a, 0xc7, 0x75, 0x84, 0xd3, 0x9d, 0xdd, 0xeb, 0xe6,
	0x6b, 0x9b, 0xfb, 0x4c, 0x74, 0xc2, 0x88, 0x09, 0x86, 0xcd, 0xa9, 0x3b, 0x0d, 0x3b, 0xf9, 0x49,
	0xeb, 0xee, 0xc4, 0x13, 0xd7, 0xf1, 0xa8, 0x33, 0x66, 0xd3, 0xee, 0x84, 0x4d, 0x58, 0x57, 0xa2,
	0x46, 0xf1, 0x33, 0x69, 0x49, 0x43, 0xae, 0x52, 0x76, 0xab, 0x5d, 0xea, 0x7e, 0xca, 0x5c, 0xea,
	0x67, 0x88, 0x4f, 0x8a, 0x0e, 0x27, 0x8c, 0x4d, 0x7c, 0xea, 0x84, 0x1e, 0xcf, 0x96, 0x5d, 0x27,
	0xf4, 0xba, 0x4e, 0x10, 0x30, 0xe1, 0x08, 0x8f, 0x05, 0x3c, 0x25, 0x9a, 0x23, 0xd8, 0x25, 0x94,
	0x0b, 0x16, 0x51, 0x42, 0xbf, 0x8b, 0x29, 0x17, 0xf8, 0x11, 0x34, 0xae, 0xa9, 0xe3, 0xd2, 0xc8,
	0xa8, 0xb6, 0x95, 0x63, 0xb5, 0xf7, 0x76, 0x67, 0x45, 0x7b, 0x27, 0xc3, 0x5d, 0x48, 0x0c, 0xc9,
	0xb0, 0xd8, 0x82, 0xed, 0x88, 0xce, 0x3c, 0xee, 0xb1, 0xc0, 0x80, 0xb6, 0x72, 0x5c, 0x23, 0x0b,
	0xdb, 0xfc, 0xa3, 0x0a, 0xb7, 0x17, 0x41, 0x78, 0xc8, 0x02, 0x4e, 0xf1, 0xe3, 0x42, 0x94, 0x77,
	0xd6, 0xa2, 0xa4, 0xc0, 0x42, 0x98, 0xcf, 0x40, 0xf5, 0x02, 0x4f, 0xd8, 0x63, 0x16, 0x3c, 0xf3,
	0x26, 0x32, 0x92, 0xda, 0x3b, 0x28, 0x70, 0x2f, 0x03, 0x4f, 0x2c, 0xf8, 0x15, 0x02, 0x09, 0xe3,
	0x4c, 0x12, 0xf0, 0xd3, 0x44, 0x26, 0x67, 0x71, 0x34, 0xa6, 0x86, 0x2a, 0xc9, 0x47, 0xeb, 0x81,
	0xe5, 0xf1, 0x92, 0x83, 0x05, 0x05, 0x2d, 0xd0, 0x78, 0x3c, 0xe2, 0xe3, 0xc8, 0x0b, 0x93, 0x22,
	0x1a, 0x5a, 0xa9, 0x8b, 0x41, 0x3c, 0xfa, 0xca, 0xf1, 0xe3, 0x65, 0x17, 0x2b, 0x34, 0xbc, 0x0f,
	0xb7, 0xa2, 0xd8, 0xa7, 0xdc, 0x68, 0x4a, 0x7e, 0xbb, 0x28, 0x21, 0xf6, 0x69, 0xd1, 0x41, 0x4a,
	0x38, 0x6d, 0x40, 0x7d, 0xc4, 0xdc, 0xb9, 0xb9, 0x0b, 0xda, 0x72, 0x96, 0xe6, 0x35, 0xe8, 0x45,
	0xe1, 0xf8, 0x01, 0x34, 0xb2, 0x4c, 0xa1, 0x5d, 0x3b, 0x56, 0x7b, 0xfb, 0x85, 0x30, 0x0f, 0x7c,
	0xf6, 0x82, 0x64, 0x10, 0x7c, 0x0f, 0xea, 0xdc, 0x0b, 0x9e, 0x67, 0x45, 0x29, 0x85, 0x4a, 0x80,
	0xf9, 0xb3, 0x02, 0x7a, 0x31, 0x41, 0x7c, 0x00, 0xcd, 0xe5, 0x04, 0x79, 0x16, 0xb1, 0xbd, 0x5e,
	0x98, 0x05, 0x26, 0x75, 0xb0, 0x4a, 0x43, 0x84, 0xfa, 0x94, 0x45, 0x69, 0x6b, 0xb6, 0x89, 0x5c,
	0xe3, 0x1b, 0x70, 0x6b, 0xcc, 0xe2, 0x40, 0xc8, 0x62, 0xd7, 0x48, 0x6a, 0xe0, 0xbb, 0xb0, 0xcb,
	0x85, 0x13, 0x09, 0x7b, 0x71, 0xeb, 0x9a, 0xf2, 0xb8, 0x29, 0x77, 0x49, 0x7e, 0xf5, 0xbe, 0x57,
	0x60, 0x6f, 0xad, 0x9c, 0xd8, 0xc9, 0xeb, 0x9f, 0xca, 0x34, 0x6e, 0xac, 0x7f, 0x0a, 0xfb, 0xff,
	0x65, 0xfd, 0xaa, 0x80, 0x3a, 0x98, 0x07, 0xe3, 0xcd, 0x66, 0x4e, 0x87, 0xda, 0x73, 0x3a, 0x97,
	0x43, 0xa0, 0x91, 0x64, 0x89, 0x07, 0xb0, 0x13, 0x39, 0xc1, 0x84, 0xda, 0x34, 0x70, 0xa5, 0x5a,
	0x8d, 0x6c, 0xcb, 0x0d, 0x2b, 0x70, 0x4b, 0xb4, 0x69, 0x25, 0xda, 0xf0, 0x0e, 0x6c, 0xbf, 0x70,
	0xc4, 0xf8, 0xda, 0xf6, 0xdc, 0x4c, 0xfc, 0x96, 0xb4, 0x2f, 0x5d, 0xd3, 0x4a, 0x8b, 0xf9, 0x75,
	0x62, 0x2e, 0x8a, 0x79, 0x02, 0x0d, 0x3a, 0xa3, 0x81, 0xe0, 0x46, 0xed, 0xc6, 0x6a, 0x5a, 0x09,
	0x80, 0x64, 0x38, 0xf3, 0x97, 0x2a, 0x68, 0x69, 0xf6, 0x9b, 0x3d, 0x06, 0xcb, 0x4a, 0x61, 0x45,
	0x29, 0x9e, 0xad, 0xbe, 0x13, 0x6a, 0xe9, 0x9c, 0x0d, 0x7c, 0x26, 0x52, 0x65, 0xe5, 0x8f, 0xc5,
	0xbf, 0x9e, 0xf6, 0xa2, 0x93, 0xff, 0x3c, 0xed, 0x45, 0x07, 0x85, 0x69, 0xdf, 0x87, 0xbd, 0x35,
	0xad, 0xe6, 0x23, 0x39, 0x87, 0x2b, 0x7b, 0x78, 0x7f, 0xd1, 0x0b, 0xe5, 0xb5, 0x03, 0xb8, 0xda,
	0x93, 0xac, 0xb5, 0xab, 0xee, 0x4e, 0x0a, 0xee, 0x5e, 0xdf, 0xda, 0xdf, 0x14, 0x68, 0x12, 0x1a,
	0xb2, 0xe4, 0x3e, 0x6d, 0x78, 0xb5, 0x67, 0x34, 0x32, 0xea, 0x6d, 0xe5, 0x78, 0x87, 0x24, 0x4b,
	0x3c, 0x02, 0x35, 0x7f, 0x86, 0xf3, 0x7e, 0xef, 0x10, 0xc8, 0xb7, 0x2e, 0x5d, 0xbc, 0x0b, 0x75,
	0x31, 0x0f, 0xd3, 0x21, 0xdd, 0xed, 0xdd, 0x59, 0x0b, 0x93, 0x88, 0x1a, 0xce, 0x43, 0x4a, 0x24,
	0x0c, 0x0d, 0xd8, 0x0a, 0x9d, 0xb9, 0xcf, 0x1c, 0x57, 0xf6, 0x55, 0x23, 0xb9, 0x69, 0x7e, 0x9e,
	0x7c, 0x12, 0xd3, 0x14, 0x36, 0xba, 0x9f, 0xef, 0xff, 0xa0, 0x00, 0xbc, 0x8a, 0x8b, 0x3a, 0x68,
	0x4f, 0xaf, 0xec, 0x8b, 0xfe, 0x93, 0xf3, 0xc1, 0x45, 0xff, 0x0b, 0x4b, 0xaf, 0xe0, 0x5b, 0x80,
	0xcb, 0x3b, 0x36, 0xb1, 0xae, 0x1e, 0x7d, 0xa3, 0x2b, 0x39, 0xd2, 0xea, 0x93, 0xe1, 0xa9, 0xd5,
	0x1f, 0xea, 0xd5, 0x1c, 0x99, 0xef, 0x64, 0xc8, 0x1a, 0x36, 0x61, 0xe7, 0xe9, 0x95, 0x3d, 0x18,
	0xf6, 0x87, 0x5f, 0x0e, 0xf4, 0x3a, 0xde, 0x06, 0x35, 0x31, 0xad, 0x27, 0xe7, 0xf6, 0xd9, 0xe3,
	0x73, 0x1d, 0xf0, 0x4d, 0xd8, 0x5b, 0xda, 0xc8, 0x68, 0x6a, 0xef, 0x47, 0x05, 0xe0, 0x21, 0x1b,
	0x3d, 0x76, 0x02, 0x67, 0x42, 0x23, 0x7c, 0x08, 0x5b, 0xd9, 0xf7, 0x19, 0x4b, 0x52, 0x5b, 0xfa,
	0x39, 0x68, 0x1d, 0xde, 0x74, 0x9c, 0x16, 0xe0, 0x44, 0xc1, 0x3e, 0xd4, 0x93, 0xd9, 0xc6, 0x56,
	0xf1, 0xea, 0xbd, 0x7a, 0xee, 0x5a, 0x07, 0xa5, 0x67, 0xb9, 0x8b, 0xd3, 0xfd, 0xdf, 0x5f, 0x1e,
	0x56, 0xfe, 0x7a, 0x79, 0x58, 0xf9, 0xe9, 0xcf, 0xc3, 0xca, 0xb7, 0xd5, 0xd9, 0xbd, 0xbf, 0x15,
	0x65, 0xd4, 0x90, 0xff, 0x2b, 0x1f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x57, 0x12, 0x08, 0x74,
	0x6b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobManagerClient is the client API for JobManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobManagerClient interface {
	// Restore return init config and snapshot data
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (JobManager_RestoreClient, error)
	// Sync return event data
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (JobManager_SyncClient, error)
}

type jobManagerClient struct {
	cc *grpc.ClientConn
}

func NewJobManagerClient(cc *grpc.ClientConn) JobManagerClient {
	return &jobManagerClient{cc}
}

func (c *jobManagerClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (JobManager_RestoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobManager_serviceDesc.Streams[0], "/mdmp.metadata.JobManager/Restore", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobManagerRestoreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobManager_RestoreClient interface {
	Recv() (*RestoreResponse, error)
	grpc.ClientStream
}

type jobManagerRestoreClient struct {
	grpc.ClientStream
}

func (x *jobManagerRestoreClient) Recv() (*RestoreResponse, error) {
	m := new(RestoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobManagerClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (JobManager_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobManager_serviceDesc.Streams[1], "/mdmp.metadata.JobManager/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobManagerSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobManager_SyncClient interface {
	Recv() (*SyncResponse, error)
	grpc.ClientStream
}

type jobManagerSyncClient struct {
	grpc.ClientStream
}

func (x *jobManagerSyncClient) Recv() (*SyncResponse, error) {
	m := new(SyncResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobManagerServer is the server API for JobManager service.
type JobManagerServer interface {
	// Restore return init config and snapshot data
	Restore(*RestoreRequest, JobManager_RestoreServer) error
	// Sync return event data
	Sync(*SyncRequest, JobManager_SyncServer) error
}

// UnimplementedJobManagerServer can be embedded to have forward compatible implementations.
type UnimplementedJobManagerServer struct {
}

func (*UnimplementedJobManagerServer) Restore(req *RestoreRequest, srv JobManager_RestoreServer) error {
	return status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (*UnimplementedJobManagerServer) Sync(req *SyncRequest, srv JobManager_SyncServer) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}

func RegisterJobManagerServer(s *grpc.Server, srv JobManagerServer) {
	s.RegisterService(&_JobManager_serviceDesc, srv)
}

func _JobManager_Restore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobManagerServer).Restore(m, &jobManagerRestoreServer{stream})
}

type JobManager_RestoreServer interface {
	Send(*RestoreResponse) error
	grpc.ServerStream
}

type jobManagerRestoreServer struct {
	grpc.ServerStream
}

func (x *jobManagerRestoreServer) Send(m *RestoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _JobManager_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobManagerServer).Sync(m, &jobManagerSyncServer{stream})
}

type JobManager_SyncServer interface {
	Send(*SyncResponse) error
	grpc.ServerStream
}

type jobManagerSyncServer struct {
	grpc.ServerStream
}

func (x *jobManagerSyncServer) Send(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _JobManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mdmp.metadata.JobManager",
	HandlerType: (*JobManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Restore",
			Handler:       _JobManager_Restore_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sync",
			Handler:       _JobManager_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "metadata/v1/metadata_slot.proto",
}
