// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata/v1/metadata_model.proto

package v1

type ResourceVersionRead interface {
	GetResourceVersion() string
}

type ResourceVersionWriter interface {
	SetResourceVersion(version string)
}

type ResourceVersionReadWriter interface {
	ResourceVersionRead
	ResourceVersionWriter
}
