// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata/v1/metadata_rpc.proto

package v1

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RpcPacket) Validate() error {
	if this.Header != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Header); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Header", err)
		}
	}
	if this.Cluster != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Cluster); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Cluster", err)
		}
	}
	return nil
}
func (this *ClusterInfo) Validate() error {
	return nil
}
func (this *RpcStatus) Validate() error {
	return nil
}
func (this *QueryAction) Validate() error {
	if this.Entity != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Entity); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Entity", err)
		}
	}
	return nil
}
